language: csharp
solution: SqlBulkTools.sln
mono: none
dotnet: 2.1.301
env:
  - PACKAGE_VERSION="2.1.$TRAVIS_BUILD_NUMBER"
script:
 - dotnet restore
 - dotnet build
 - dotnet test SqlBulkTools.NetStandard.UnitTests/SqlBulkTools.NetStandard.UnitTests.csproj
 - dotnet pack --no-restore --no-build --include-symbols /p:PackageVersion=$PACKAGE_VERSION
 - if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_PULL_REQUEST" == "false" ) ]]; then dotnet nuget push **/SqlBulkTools.NetStandard.$PACKAGE_VERSION.nupkg -k $ApiKey -s https://api.nuget.org/v3/index.json; fi
