language: csharp
solution: SqlBulkTools.sln
mono: none
dotnet: 2.1.301
script:
 - dotnet restore
 - dotnet build
 - dotnet test SqlBulkTools.NetStandard.UnitTests/SqlBulkTools.NetStandard.UnitTests.csproj